# Generated by Django 4.2.7 on 2025-06-05 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        ('analytics', '0002_initial'),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamanalytics',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='teams.team'),
        ),
        migrations.AddField(
            model_name='playerstatistic',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_statistics', to='games.game'),
        ),
        migrations.AddField(
            model_name='playerstatistic',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_statistics', to='teams.team'),
        ),
    ]
