# Generated by Django 4.2.7 on 2025-06-05 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='standing',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
        ),
    ]
